<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Prximo Paso   Por favor espere</name>
   <tag></tag>
   <elementGuidId>6b1a885e-1d6c-40e1-b5ad-18ae19681b28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-register']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-register</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4f5fc8b5-f7be-438d-890b-2108bf680529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-register</value>
      <webElementGuid>3b79c4e1-ddcf-42d9-beb6-9e193e8e6ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b946acaf-4762-4cf4-b202-d4fef21f5cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-create-account btn btn-block</value>
      <webElementGuid>1b7b81de-10cf-43ed-a27b-ece7ae5f6721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Próximo Paso   Por favor espere </value>
      <webElementGuid>57d4565d-7ab1-4cd6-82b3-165d4177024a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-register&quot;)</value>
      <webElementGuid>2f07dffc-62ad-4d00-a858-766436cae770</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-register']</value>
      <webElementGuid>3777ddfb-8d66-4e2e-a0ca-3a5faf35a525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[7]/div[2]/button</value>
      <webElementGuid>01d2306e-f69f-420a-90e6-dc8a8d96099b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/button</value>
      <webElementGuid>add47153-174d-445a-a0ed-734486406a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-register' and @type = 'submit' and (text() = 'Próximo Paso   Por favor espere ' or . = 'Próximo Paso   Por favor espere ')]</value>
      <webElementGuid>1a8efbc8-cbb5-4271-9659-cfafd21bf1f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
