<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Crear una cuenta de Mobipaid</name>
   <tag></tag>
   <elementGuidId>5d337927-6418-4f8d-aa86-83dccb58ea99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='body']/div[2]/div/div/div/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-lg-6.col-md-5.mrt-margin-bot</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9a0bc28c-3e34-43af-a27c-b4596a10375f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-lg-6 col-md-5 mrt-margin-bot</value>
      <webElementGuid>45ba67ff-a431-4389-995b-b59a4f645612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Crear una cuenta de Mobipaid</value>
      <webElementGuid>be1caf3a-3848-4cda-b5cf-1327479f2964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;register-wrapper&quot;]/div[@class=&quot;register-padding&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-7 col-md-7 register-mobi-right&quot;]/div[@class=&quot;text-center logo-marg visible-xs visible-sm&quot;]/div[@class=&quot;col-lg-6 col-md-5 mrt-margin-bot&quot;]</value>
      <webElementGuid>e66231ae-81e0-4c80-9266-fd8a992dab8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body']/div[2]/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>fd6ea563-38d2-4e6a-8d55-06c6fee3ca91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>d76fa89c-5af5-4b7e-b0a9-d8ed0708cf11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Crear una cuenta de Mobipaid' or . = 'Crear una cuenta de Mobipaid')]</value>
      <webElementGuid>4b07b531-92ad-4bb1-ae52-9088f278f769</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
