<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Account successfully created</name>
   <tag></tag>
   <elementGuidId>1fcd3b3d-3052-4f53-9b06-8859d8aa8ed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='success-mob']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#success-mob</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e87f7669-e677-48e9-a663-5338ff10e65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile-alert alert-success col-md-12 animated fadeInDown</value>
      <webElementGuid>bd81a392-5cec-4451-a775-5426469a3c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>success-mob</value>
      <webElementGuid>0acf05c6-6fda-4315-a5d9-7fdb9fcc62fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account successfully created</value>
      <webElementGuid>440ee2ae-242e-4890-8a00-d401d3e3929f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;success-mob&quot;)</value>
      <webElementGuid>75e8c5d2-258c-4ba4-9f00-9bc909cdee05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='success-mob']</value>
      <webElementGuid>9d8d8425-f9dd-4fe2-8d33-cf62eab88b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[2]/div/div[2]</value>
      <webElementGuid>8965af8c-95e9-4ba3-aeab-7aae65ee92c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div[2]</value>
      <webElementGuid>559d705e-d5f7-4d77-8a6d-a301714dbfb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'success-mob' and (text() = 'Account successfully created' or . = 'Account successfully created')]</value>
      <webElementGuid>07a45ef0-1728-476d-93d8-1e063f466ef8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
